### ISSUE TITLE
Paste link title into selected link url

### ISSUE THREAD

**Issue by NomarCub** [jose-elias-alvarez/obsidian-paste-link#1]
The [original plugin](https://github.com/denolehov/obsidian-url-into-selection) had this capability.
Described in detail here: https://github.com/mii-key/obsidian-links/issues/13

**Comment by jose-elias-alvarez** [comment]
This isn't something I personally use, but I'm happy to review and accept a PR adding it as a separate command. If you're not up for it, let me know and I can put something together.

**Comment by NomarCub** [comment]
I probably won't have the time for this soon, but I'm fine if that's what it takes. Could you provide some pointers to how you'd do it? It doesn't seem complicated, but I want to be on the right path.
Just so that we are on the same page (you said "separate command"): I'd like to have it as a command that combines both behaviours, contextually. See here (excluding fetching): https://github.com/mii-key/obsidian-links/issues/22#issuecomment-1869143345

**Comment by jose-elias-alvarez** [comment]
In terms of the logic, it should be pretty simple: get the current selection, check if it looks like a Markdown link, and if so replace the existing title with the current clipboard content.

If you'd like to add the behavior to the existing command, that'll take some more work, since the plugin already does something when pasting if a link is selected: if the clipboard contains a URL, it replaces the link's current URL with the clipboard URL. It might make sense to add a config option to define what happens in this case.

**Comment by WinHex89** [comment]
Can you support such URLs like [00:25:07.266](ziyunote://play?path=F:\course\meida\01PR\test.mp4&time=00:25:07.266)

**Comment by WinHex89** [comment]
Can you support such URLs like `[00:25:07.266](ziyunote://play?path=F:\test\course.mp4&time=00:25:07.266)`

**Comment by jose-elias-alvarez** [comment]
> Can you support such URLs like `[00:25:07.266](ziyunote://play?path=F:\test\course.mp4&time=00:25:07.266)`

Sorry for the late reply, just saw this. What exactly do you want to happen in this case? Pasting `ziyunote://play?path=F:\test\course.mp4&time=00:25:07.266` into Obsidian with the plugin enabled works as expected:

![Screenshot 2024-11-17 at 11 20 30 AM](https://github.com/user-attachments/assets/2117e159-4ea1-4640-974d-07f291d90d65)

**Comment by jose-elias-alvarez** [comment]
I'm going to close this, since as I understand it, obsidian-links (which is essentially a much larger and full-featured version of this plugin)  has this feature.
