### ISSUE TITLE
question: how does this improve on previous plugin?

### ISSUE THREAD

**Issue by eatallyourdarlings** [jose-elias-alvarez/obsidian-paste-link#3]
Hey just wanted to ask how exactly this improves on [obsidian-url-into-selection](https://github.com/denolehov/obsidian-url-into-selection), which you mention in passing in the README?

**Comment by jose-elias-alvarez** [comment]
Thanks for raising this, since I can see that it's unclear. There's a few things that motivated me to make this:

- A hotkey (Shift) to paste a link as plain text
- An option to disable overriding the paste handler and use a dedicated command instead
- A desire to clean up the code, which also resulted in fixing bugs I would occasionally encounter

I've added these to the README in da01775.
